title: Saurabh Harak
description: Senior Software Engineer - AI Platforms | Building Enterprise RAG, LLM Evaluation & Agentic AI Systems at Scale

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

# Site variables
author: Saurabh Dattatray Harak
job_title: Senior Software Engineer – AI Platforms
email: jobsforsaurabhharak@gmail.com
linkedin: https://linkedin.com/in/saurabh-harak
github_username: saurabhharak
phone: "+91-7719012555"
